server:
  # 服务运行端口
  port: 8002

spring:
  application:
    # 指定服务名称
    name: eureka-server
eureka:
  instance:
    # 指定主机地址
    hostname: replica1
  client:
    # 指定是否要从注册中心获取服务（注册中心不需要开启）
    fetch-registry: true
    # 指定是否要注册到注册中心（注册中心不需要开启）
    register-with-eureka: true
    service-url:
      defaultZone: http://replica2:8003/eureka/ # 注册到另一个注册中心
